Add troubleshooting section #48
Woodi-dev/Among-Us-Sheriff-Mod pull request #73
Opened 2021-01-22 11:39 UTC by LeoMouyna

- Add troubleshooting section on readme documentation.
- Solve missing cpp libs problem.

2021-01-22 15:15 UTC, TomDufall requested changes
A few suggestions for readability/fixing some typos.

2021-01-22 15:15 UTC, TomDufall commented on README.md
> +<p>To check if installation succeed<p>
```suggestion
<p>Verifying installation success<p>
```

2021-01-22 15:15 UTC, TomDufall commented on README.md
> +  <li>On top, left corner, below among us version you should see <em>loaded Sheriff Mod vx.y by Woodi </em>
```suggestion
  <li>In the top-left corner, below Among Us version, you should see <em>loaded Sheriff Mod vx.y by Woodi </em>
```

2021-01-22 15:15 UTC, TomDufall commented on README.md
> +  <li>You migh missing some cpp libs, please install
```suggestion
  <li>You might be missing some cpp libs (software libraries used by the mod); please install 
```

2021-01-22 15:15 UTC, TomDufall commented on README.md
> +  <li>Make sure you followed all <a href="#installation">instalation steps</a>, especially launching game via Among Us.exe file</li>
```suggestion
  <li>Make sure you have followed all the <a href="#installation">installation steps</a>, especially launching the game via the Among Us.exe file</li>
```

2021-01-22 15:15 UTC, TomDufall commented on README.md
> +You can add a <a href="https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/issues/new">github issue</a> explaining your case once loged in.
```suggestion
You can <a href="https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/issues/new">raise an issue within GitHub</a> documenting your issue. You will need to be logged into GitHub to do this.
```

2021-01-22 15:46 UTC, LeoMouyna commented
> A few suggestions for readability/fixing some typos.

@TomDufall, thanks for your review :)

2021-01-27 20:12 UTC, merged

2021-05-22 00:30 UTC, dhari2 commented
ع